import type { Appliance } from '../types';

export const APPLIANCE_PRESETS: Appliance[] = [
  {
    id: 'ac-inverter-12k',
    name: 'แอร์ Inverter (9,000 - 12,000 BTU)',
    nameEn: 'Inverter Air Conditioner',
    category: 'cooling',
    watts: 750,
    defaultHoursPerDay: 8,
    icon: 'Snowflake',
    description: 'แอร์ประหยัดไฟเบอร์ 5 อินเวอร์เตอร์ กินไฟเฉลี่ย 600 - 900W',
    efficiencyNote: 'ตั้ง 26°C + พัดลม ประหยัดเพิ่ม ~10%',
  },
  {
    id: 'ac-fixed-12k',
    name: 'แอร์ธรรมดา Fixed Speed (12,000 BTU)',
    nameEn: 'Non-Inverter Air Conditioner',
    category: 'cooling',
    watts: 1100,
    defaultHoursPerDay: 8,
    icon: 'Wind',
    description: 'แอร์รุ่นเก่า/ตัดต่อคอมเพรสเซอร์ กินไฟสูงกว่าอินเวอร์เตอร์',
    efficiencyNote: 'คอมเพรสเซอร์ตัด-ต่อทำงานเต็มกำลัง',
  },
  {
    id: 'gaming-pc',
    name: 'คอมพิวเตอร์ตั้งโต๊ะ / Gaming PC',
    nameEn: 'Gaming Desktop PC',
    category: 'entertainment',
    watts: 350,
    defaultHoursPerDay: 5,
    icon: 'Monitor',
    description: 'CPU + การ์ดจอแยก เล่นเกมหรือตัดต่อกราฟิก',
  },
  {
    id: 'water-heater',
    name: 'เครื่องทำน้ำอุ่น (3,500W)',
    nameEn: 'Instant Water Heater',
    category: 'heating',
    watts: 3500,
    defaultHoursPerDay: 0.5,
    icon: 'Flame',
    description: 'กำลังวัตต์สูงมาก แต่เปิดช่วงเวลาสั้นๆ ตอนอาบน้ำ',
  },
  {
    id: 'refrigerator',
    name: 'ตู้เย็น 1-2 ประตู (5 - 8 คิว)',
    nameEn: 'Refrigerator',
    category: 'kitchen',
    watts: 80,
    defaultHoursPerDay: 24,
    icon: 'Box',
    description: 'เสียบปลั๊ก 24 ชม. คอมเพรสเซอร์ทำงานตัดต่อ 8-12 ชม./วัน',
  },
  {
    id: 'standing-fan',
    name: 'พัดลมตั้งพื้น 16-18 นิ้ว',
    nameEn: 'Standing Fan',
    category: 'cooling',
    watts: 50,
    defaultHoursPerDay: 10,
    icon: 'Fan',
    description: 'กินไฟน้อยมาก เปิดทั้งคืนไม่เปลือง',
  },
  {
    id: 'kettle',
    name: 'กาต้มน้ำร้อนไฟฟ้า (1,500W)',
    nameEn: 'Electric Kettle',
    category: 'kitchen',
    watts: 1500,
    defaultHoursPerDay: 0.2,
    icon: 'Coffee',
    description: 'ต้มน้ำร้อน มาม่า ชงกาแฟ',
  },
  {
    id: 'hair-dryer',
    name: 'ไดร์เป่าผม (1,800W)',
    nameEn: 'Hair Dryer',
    category: 'general',
    watts: 1800,
    defaultHoursPerDay: 0.3,
    icon: 'Zap',
    description: 'เป่าผมความร้อนสูง กินไฟเทียบเท่าเตารีด',
  },
  {
    id: 'induction-cooker',
    name: 'เตาแม่เหล็กไฟฟ้า / หม้อชาบู',
    nameEn: 'Induction Cooker',
    category: 'kitchen',
    watts: 1800,
    defaultHoursPerDay: 0.8,
    icon: 'CookingPot',
    description: 'ทำอาหาร ปิ้งย่าง สุกี้ในห้องพัก',
  },
  {
    id: 'laptop-work',
    name: 'โน้ตบุ๊กทำงาน / จอแยก',
    nameEn: 'Laptop & Monitor',
    category: 'entertainment',
    watts: 85,
    defaultHoursPerDay: 8,
    icon: 'Laptop',
    description: 'โน้ตบุ๊กทำงานทั่วไป ชาร์จแบตและเปิดจอเสริม',
  },
];
